### ISSUE TITLE
Simple App play on windows doesn't work, infinite loop on the terminal

### ISSUE THREAD

**Issue by Arryk** [FedeClaudi/Term.jl#253]
```julia
using Term
using Term.LiveWidgets

app = App(
  Term.Pager("This is a pager. It lets you display a lot of text in a scrollable window."^300)
);

play(app)
```

The app is continuously running the last lines in an infinite loop and keyboard is not working.

I am running it on Windows 11 using Julia 1.10.4 on Term version 2.0.6

Is this a normal issue on Windows ?

<img width="1100" alt="image" src="https://github.com/FedeClaudi/Term.jl/assets/12896037/d18bf48b-c106-460d-98c3-27a990a505b3">

**Comment by t-bltg** [comment]
Fixed by https://github.com/FedeClaudi/Term.jl/pull/258.

**Comment by davidanthoff** [comment]
This is actually not fixed, still happening on `master` on Windows in the standard terminal.
